### ISSUE TITLE
Bug Inventory Tab

### ISSUE THREAD

**Issue by ontic** [vpietri/ADM_Warehouse#3]
Because you have chosen to inject (override) the product inventory tab using an observer (using XML layout updates would be better) for both new and edit actions, an error is thrown when creating a new product

A quick fix to this problem is shown below.

https://github.com/vpietri/ADM_Warehouse/blob/master/app/code/community/ADM/Warehouse/Block/Adminhtml/Catalog/Product/Edit/Tab/Inventory.php#L28

You can simply replace the `getQtysByWarehouse()` function with what I've written below.

```
public function getQtysByWarehouse()
{
    if (!$this->_item_by_warehouses instanceof ADM_Warehouse_Model_CatalogInventory_Resource_Stock_Collection)
    {
        $warehouses = Mage::getModel('cataloginventory/stock')->getCollection();

        if ($stockItem = $this->getStockItem())
        {
            foreach ($warehouses as $warehouse)
            {
                foreach ($stockItem->getStockDetails() as $stockDetail)
                {
                    if ($stockDetail['stock_id'] == $warehouse->getId())
                    {
                        $warehouse->setQty($stockDetail['qty']);
                        $warehouse->setItemId($stockDetail['item_id']);
                    }
                }
            }
        }

        $this->_item_by_warehouses = $warehouses;
    }

    return $this->_item_by_warehouses;
}
```

All I've done is check that a stock item can be retrieved, and skip trying to set stock details for each warehouse if it cannot. The reason for the error was due to trying to retrieve the stock item from the product, when the product hadn't even been created yet.

**Comment by vpietri** [comment]
Fix applied.

**Comment by ontic** [comment]
I re-factored this fix so you're not unnecessarily looping over the warehouses
